#!/bin/bash
if [ $# == 0 ]
  then
    nano
fi
if [ $# == 1 ]
  then
    if [ -e "$1.c" ]
      then
        gcc "$1.c" -o "$1.out"
        ./"$1.out"
      else
        echo "$1.c not found"
    fi
fi
